# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

M3_vec <- function(x, xbar, S) {
    .Call(`_PPcovMcd_M3_vec`, x, xbar, S)
}

M4_matrix <- function(x, xbar, S) {
    .Call(`_PPcovMcd_M4_matrix`, x, xbar, S)
}

M4_vec <- function(x, xbar, S) {
    .Call(`_PPcovMcd_M4_vec`, x, xbar, S)
}

M34_vec <- function(x, xbar, S) {
    .Call(`_PPcovMcd_M34_vec`, x, xbar, S)
}

ML_objective <- function(par, x, nargout = 1L) {
    .Call(`_PPcovMcd_ML_objective`, par, x, nargout)
}

ML_projector <- function(par, sigma_min) {
    .Call(`_PPcovMcd_ML_projector`, par, sigma_min)
}

arma_ast <- function(A, B) {
    .Call(`_PPcovMcd_arma_ast`, A, B)
}

mah_standard <- function(x, loc, cov, rank) {
    .Call(`_PPcovMcd_mah_standard`, x, loc, cov, rank)
}

proj_orth_comp <- function(x, dir) {
    .Call(`_PPcovMcd_proj_orth_comp`, x, dir)
}

mcd1D <- function(x, h) {
    .Call(`_PPcovMcd_mcd1D`, x, h)
}

mcd1D_grad <- function(x, best) {
    .Call(`_PPcovMcd_mcd1D_grad`, x, best)
}

PP_objective <- function(xp, best) {
    .Call(`_PPcovMcd_PP_objective`, xp, best)
}

PP_gradient <- function(xp, x, best) {
    .Call(`_PPcovMcd_PP_gradient`, xp, x, best)
}

PP_project <- function(dir) {
    .Call(`_PPcovMcd_PP_project`, dir)
}

